#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "ELETROLUCAS-2"
  https://create.arduino.cc/cloud/things/62e677b0-96fb-483a-8a98-2d3637365693

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes
  are made to the Thing

  AS VARIÁVEIS DEFINIDAS NA CLOUD ESTARÃO AQUI

  Variables which are marked as READ/WRITE in the Cloud Thing will also have
  functions which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this
  sketch.
*/

#include "thingProperties.h"
#include <rtos.h>

using namespace mbed;
using namespace rtos;

// Variáveis para controle de modo offline
bool modoOffline = false;
bool cloudConectado = false;
bool cloudSincronizado = false; // Flag para indicar se a sincronização inicial foi concluída
unsigned long ultimaConexaoCloud = 0;
int tentativasConexao = 0;

// Thread para execução do ArduinoCloud
rtos::Thread cloudThread(osPriorityNormal, 8192); // 8KB stack

void cloudThreadFunc() {
  while (true) {
    // Executa o update da nuvem em uma thread separada
    // Se bloquear aqui (ex: DHCP), não afeta o loop principal
    // IMPORTANTE: Esta thread funciona independente da presença de USB
    // O NetworkConfigurator com SerialAgent não deve bloquear esta thread
    ArduinoCloud.update();
    
    // Pequeno delay para ceder CPU - otimizado para não causar delays desnecessários
    rtos::ThisThread::sleep_for(10);
  }
}

void setup() {
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  // Configura LEDs de status ANTES de qualquer inicialização (feedback visual imediato)
  pinMode(LED_USER, OUTPUT); // LED azul para conexão Cloud
  pinMode(LEDR, OUTPUT);     // LED vermelho para modo offline
  digitalWrite(LED_USER, LOW);  // LED azul desligado
  digitalWrite(LEDR, HIGH);     // LED vermelho ligado (modo offline inicial)

  // Defined in thingProperties.h
  initProperties();

  // Garante inicialização adequada do Ethernet antes do Cloud
  // O EthernetConnectionHandler deve inicializar automaticamente, mas garantimos
  // que não haja dependência de Serial para isso funcionar sem USB
  
  // Connect to Arduino IoT Cloud
  // IMPORTANTE: false desabilita o watchdog interno que causa reinícios
  // CORREÇÃO: Inicialização robusta que funciona mesmo sem USB conectado
  // O NetworkConfigurator com SerialAgent não deve bloquear - ele tenta Serial mas
  // não deve travar se não houver USB disponível
  ArduinoCloud.begin(ArduinoIoTPreferredConnection, false);
  
  /*
     OTIMIZAÇÃO: Reduz mensagens de debug para evitar overhead
     0 = apenas erros (recomendado para produção)
     2 = debug completo (use apenas para troubleshooting)
  */
  //setDebugMessageLevel(0);
  //ArduinoCloud.printDebugInfo();
  
  // Adiciona callbacks para eventos de conectividade
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, onCloudConnect);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::SYNC, onCloudSync);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, onCloudDisconnect);


  // GARANTE: Sistema sempre funciona offline-first
  modoOffline = true;
  cloudConectado = false;
  cloudSincronizado = false; // Inicializa como não sincronizado

  // Inicia a thread da nuvem DEPOIS de toda a inicialização
  // Isso garante que o Ethernet e todos os componentes estejam prontos
  // antes de tentar conectar à nuvem, evitando problemas quando não há USB
  cloudThread.start(cloudThreadFunc);
  
  // Pequeno delay final para garantir que tudo esteja estabilizado
  // antes de entrar no loop principal - ajuda na reconexão quando não há USB
  delay(100);
}

void loop() {
  // Verificação de conectividade (executada periodicamente, não bloqueia)
  static unsigned long ultimaVerificacao = 0;
  if ((millis() - ultimaVerificacao) >= 10000) { // Verifica a cada 10 segundos
    verificarStatusConectividade();
    ultimaVerificacao = millis();
  }


  //O SEU CÓDIGO PRINCIPAL PODE FICAR LOGO ABAIXO DESSA LINHA, É IMPORTANTE QUE ESTÁ ABAIXO DA FUNÇÃO MILLIS ACIMA.

  
  //O TRECHO ABAIXO É UM EXEMPLO DE COMO USAR OS WIDGETS DE STATUS DA CLOUD, ESSA É A FORMA CORRETA
  //CASO NÃO SEJA FEITA DESSA FORMA, AO REINICIAR O PRODUTO, O OPTA IRÁ TRAVAR E NÃO SE CONECTARÁ NA INTERNET
  //DA FORMA QUE FOI CONSTRUÍDO, SÓ IRÁ ATUALIZAR AS VARIÁVEIS DE FEEDBACK QUANDO DE FATO O OPTA ESTIVER CONECTADO E SINCRONIZADO COM A INTERNET E CLOUD

  // Só atualiza variáveis da cloud se estiver conectado E sincronizado
  // Isso evita problemas de conexão ao reiniciar o dispositivo
  if(cloudConectado && cloudSincronizado) {
    
    //FEEDBACK DE DISJUNTOR ABERTO
    if(fbAbertura == HIGH){
      feedbackabertura = HIGH;
    }else{
      feedbackabertura = LOW;
    }

    //FEEDBACK DE DISJUNTOR FECHADO
    if(fbFechamento == HIGH){
      feedbackfechamento = HIGH;
    }else{
      feedbackfechamento = LOW;
    }

    //FEEDBACK DE MOLA CARREGADA
    if(fbMolaCarregada == HIGH){
      feedbackmolacarregada = HIGH;
    }else{
      feedbackmolacarregada = LOW;
    }

  }


}

// Função para verificar status de conectividade (backup para callbacks)
void verificarStatusConectividade() {
  bool agoraConectado = ArduinoCloud.connected();
  
  if (agoraConectado && !cloudConectado) {
    // Conectou agora
    onCloudConnect();
  } else if (!agoraConectado && cloudConectado) {
    // Desconectou agora
    onCloudDisconnect();
  }
}

// Callbacks para eventos de conectividade IoT Cloud
void onCloudConnect() {
  cloudConectado = true;
  modoOffline = false;
  cloudSincronizado = false; // Reset: aguarda sincronização antes de atualizar variáveis
  ultimaConexaoCloud = millis();
  tentativasConexao = 0;
  
  // Atualiza LEDs de status
  digitalWrite(LED_USER, HIGH); // LED azul ligado (Cloud conectado)
  digitalWrite(LEDR, LOW);       // LED vermelho desligado
}

void onCloudSync() {
  // Sincronização concluída - agora é seguro atualizar variáveis da cloud
  cloudSincronizado = true;
}

void onCloudDisconnect() {
  cloudConectado = false;
  cloudSincronizado = false; // Reset: não está mais sincronizado
  modoOffline = true;
  
  // Atualiza LEDs de status
  digitalWrite(LED_USER, LOW);  // LED azul desligado
  digitalWrite(LEDR, HIGH);     // LED vermelho ligado (modo offline)
  
  // Reinicia o contador de tentativas após desconexão inesperada
  tentativasConexao = 0;
}

